DROP TABLE IF EXISTS 'WSMSG_FUNDSELECTOR';
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE 'WSMSG_FUNDSELECTOR' (
  'SEQUENCENO' int(11) NOT NULL AUTO_INCREMENT,
  'FUND_CODE' varchar(100) NOT NULL,
  'FUND_DESCRIPTION' varchar(100) DEFAULT NULL,
  'FUND_MANAGER' varchar(400) DEFAULT NULL,
  'FUND_NAME' varchar(400) DEFAULT NULL,
  'LAUNCH_DATE' varchar(400) DEFAULT NULL,
  'MINIMUM_INVESTMENT_INITIAL' varchar(400) DEFAULT NULL,
  'MINIMUM_INVESTMENT_SUBSEQUENT' varchar(400) DEFAULT NULL,
  'CPFIS' varchar(400) DEFAULT NULL,
  'GEOGRAPHIC_REGION' varchar(400) DEFAULT NULL,
  'SPECIALIST_SECTOR' varchar(400) DEFAULT NULL,
  'ASSET_TYPE' varchar(400) DEFAULT NULL,
  'PRODUCT_RISK_CLASSIFICATIONS' varchar(400) DEFAULT NULL,
  'LINK_TO_FACT_SHEET' varchar(400) DEFAULT NULL,
  'LINK_TO_PROSPECTUS' varchar(400) DEFAULT NULL,
  'LINK_TO_PRODUCT_HIGHLIGHTS' varchar(400) DEFAULT NULL,
  'LINK_TO_ANNUAL_REPORT' varchar(400) DEFAULT NULL,
  'PIB' varchar(400) DEFAULT NULL,
  'NAV2' varchar(50) DEFAULT NULL,
  'NAV' varchar(50) DEFAULT NULL,
  'AS_AT_DATE' varchar(400) DEFAULT NULL,
  PRIMARY KEY ('SEQUENCENO')
);
